import React, { memo } from 'react';
import { Avatar, Pane, Heading, majorScale } from 'evergreen-ui';

export const AvatarsComponent: React.FC = () => (
  <Pane>
    {[false, true].map((solid) => (
      <Pane key={String(solid)} marginTop={majorScale(3)}>
        <Heading is="h3" size={500} marginBottom={majorScale(1)}>
          {solid ? 'Solid' : 'Subtle'} Avatar
        </Heading>
        <Avatar name="Fast Nguyen" size={40} isSolid={solid} />
      </Pane>
    ))}
    <Pane marginTop={majorScale(3)}>
      <Heading is="h3" size={500} marginBottom={majorScale(1)}>
        Avatar with image
      </Heading>
      <Avatar
        src="https://upload.wikimedia.org/wikipedia/commons/a/a1/Alan_Turing_Aged_16.jpg"
        name="Alan Turing"
        size={40}
      />
    </Pane>
    <Pane marginTop={majorScale(3)}>
      <Heading is="h3" size={500} marginBottom={majorScale(1)}>
        Avatar with color generated by name
      </Heading>
      <Pane display="flex" gap={majorScale(2)}>
        {['Fast Nguyen', 'Theodore Nguyen', 'Marcus Nguyen'].map((name) => (
          <Avatar key={name} name={name} size={40} />
        ))}
      </Pane>
    </Pane>
    <Pane marginTop={majorScale(3)}>
      <Heading is="h3" size={500} marginBottom={majorScale(1)}>
        Manually override the color
      </Heading>
      <Avatar name="Fast Nguyen" size={40} color="green" />
    </Pane>
    <Pane marginTop={majorScale(3)}>
      <Heading is="h3" size={500} marginBottom={majorScale(1)}>
        Rendering anonymous users with different colors
      </Heading>
      <Pane display="flex" gap={majorScale(2)}>
        <Avatar hashValue="id_124" name="Anonymous User" size={40} />
        <Avatar hashValue="id_249" name="Anonymous User" size={40} />
        <Avatar hashValue="id_299" name="Anonymous User" size={40} />
      </Pane>
    </Pane>
  </Pane>
);

const Avatars = memo(AvatarsComponent);
Avatars.displayName = 'Avatars';

export default Avatars;
